# Problem 1 

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
snn = np.array([70,25,13,44,55])
print(snn)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
snn.sort()
print(snn)


[70 25 13 44 55]
[13 25 44 55 70]


# Problem 2

In [56]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
deger = np.array([10,15,30,45,60])
print(deger)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
x = np.arange(5,15)
print(x)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange(50,100,5)
print(c)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
print(np.zeros(10))

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
print(np.ones(10))

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
a = np.linspace(0,100,5)
print(a)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
print(np.random.randint(10,30,5))
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
z= np.linspace(-1,1,10)
print(z)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
sayi = np.random.randint(10,50, size=(3,5))
print(sayi)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(sayi.shape)
rows, cols = sayi.shape
topl = rows + cols
print(topl)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(sayi.max())
print(sayi.min())
print(sayi.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
indeks = np.unravel_index(np.argmax(sayi), sayi.shape)
a = sayi.max()
print("En büyük değer:", a)
print("En büyük değerin indeksi:", indeks)
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
y = np.arange(10,20)
print(y[0:3:])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(y[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
sayi = np.random.randint(10,50, size=(3,5))
print(sayi[0])
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(sayi[2,3])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(sayi[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.power(sayi,2))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
cift = np.arange(-50, 50)
sonux =  (cift > 0) & (cift % 2==0) 
a = cift[sonux]
print(cift)
print(a)

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[14 28 20 19 14]
[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]
[[49 20 17 38 33]
 [12 28 30 36 47]
 [28 10 19 25 22]]
(3, 5)
8
49
10
27.6
En büyük değer: 49
En büyük değerin indeksi: (np.int64(0), np.int64(0))
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[48 47 12 27 26]
31
[48 30 18]
[[2304 2209  144  729  676]
 [ 900  484  625  324  529]
 [ 324  576  121  961 1681]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]
