# Problem 1

In [10]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
x = np.array([1,2,3,4,5,6,7,8,9,10])
multi = x.reshape(2,5)
print(multi)
# 3 - matris'in boyutunu öğrenin
print(x.shape)
print(multi.shape)
# 4 - matris'i yeniden boyutlandırın
new = x.reshape(5,2)
print(new)
# 5 - matris'in boyut sayısını öğrenin
print(new.ndim)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(10,)
(2, 5)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


# Problem 2

In [16]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a = np.arange(1,10,2)
print(a)

# 2 - Oluşturduğunuz matrisi parçalayın
b= np.split(a,[1,2])
print(b)
# 3 - Parçalanmış matrisleri birleştirin
c = np.concatenate(b)
print(c)


[1 3 5 7 9]
[array([1]), array([3]), array([5, 7, 9])]
[1 3 5 7 9]


# Problem 3

In [18]:
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
import random
son = list(range(5, 101, 2))
random_numbers = random.sample(son , 10)
sonuc= np.array(random_numbers).reshape(2,5)
print(sonuc)
# 2 - matris'in özelliklerini inceleyin


[[85 49  9 95 11]
 [15 29 21 37 17]]
